apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: proxy-gw
  namespace: aerospike
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 4000
        name: grpc
        protocol: GRPC
      hosts:
        - "*"
      tls:
        mode: PASSTHROUGH
