apiVersion: v2
name: aerospike-esp-outbound
description: A Helm chart for Aerospike Connect for ESP - Outbound
type: application
icon: https://avatars0.githubusercontent.com/u/2214313?s=200&v=4
keywords:
  - Aerospike
  - ESP
  - Connector
  - Outbound
  - Source
maintainers:
  - name: Aerospike
    email: developers@aerospike.com

# The helm chart version
version: "2.4.14"

# The default version of Aerospike ESP Outbound Connector
appVersion: "2.4.14"