backendUri: http://{{ $.Values.restbackend.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.restbackend.port.number }}
storageProviderUri: http://{{ $.Values.storageprovider.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.storageprovider.port.number }}
httpHost: {{ $.Values.queuehandler.config.host }}
httpPort: {{ $.Values.queuehandler.port.number }}
backendTimeoutMs: {{ $.Values.queuehandler.config.backendTimeoutMs }}
backendQueueProcessingTimeoutMs: {{ $.Values.queuehandler.config.backendQueueProcessingTimeoutMs }}
authenticatorUri: http://{{ $.Values.authenticator.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.authenticator.port.number }}
auth:
  enabled: {{ $.Values.queuehandler.config.auth.enabled }}
  tokenRefreshSeconds: {{ $.Values.queuehandler.config.auth.tokenRefreshSeconds }}
  username: {{ $.Values.queuehandler.config.auth.username }}
  password: {{ $.Values.queuehandler.config.auth.password }}
queueBatchSize: {{ $.Values.queuehandler.config.queueBatchSize }}
queueBatchDurationLimitMs: {{ $.Values.queuehandler.config.queueBatchDurationLimitMs }}
queuePullingIntervalMs: {{ $.Values.queuehandler.config.queuePullingIntervalMs }}
zombieRecoverIntervalMs: {{ $.Values.queuehandler.config.zombieRecoverIntervalMs }}
recordRecoverThresholdMs: {{ $.Values.queuehandler.config.recordRecoverThresholdMs }}
retryIntervalMs: {{ $.Values.queuehandler.config.retryIntervalMs }}
meterRegistryStepSeconds: {{ $.Values.queuehandler.config.meterRegistryStepSeconds }}
refreshQueueDetailsCacheSeconds: {{ $.Values.queuehandler.config.refreshQueueDetailsCacheSeconds }}
processingExecutorSize: {{ $.Values.queuehandler.config.processingExecutorSize }}
circuitBreakerConfiguration:
  slidingWindowSize: {{ $.Values.queuehandler.config.circuitBreakerConfiguration.slidingWindowSize }}
  minimumNumberOfCalls: {{ $.Values.queuehandler.config.circuitBreakerConfiguration.minimumNumberOfCalls }}
  slowCallDurationThreshold: {{ $.Values.queuehandler.config.circuitBreakerConfiguration.slowCallDurationThreshold }}
  permittedNumberOfCallsInHalfOpenState: {{ $.Values.queuehandler.config.circuitBreakerConfiguration.permittedNumberOfCallsInHalfOpenState }}
  automaticTransitionFromOpenToHalfOpenEnabled: {{ $.Values.queuehandler.config.circuitBreakerConfiguration.automaticTransitionFromOpenToHalfOpenEnabled | quote }}
  waitDurationInOpenState: {{ $.Values.queuehandler.config.circuitBreakerConfiguration.waitDurationInOpenState }}