replicas: 1
image:
  repository: ""
  pullPolicy: "Always"
  tag: "latest"
annotations:
  "co.elastic.logs/enabled": "true"
labels: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
nameOverride: ""
fullnameOverride: ""
resources: { }

aws:
  ecrtokenissuer:
    enabled: false
    issuer:
      name: "ecr-token-issuer"
    secretname: "regcred"
    credentials:
      awsAccountId: ""
      awsRegion: ""
      awsAccessKeyId: ""
      awsSecretAccessKey: ""

sourceclusters:
  nameprefix: "source-cluster"
  addresses:
    ips: [ ]
    dnsnames: [ ]
  port:
    name: "source-port"
    number: 3000
  auth:
    username: "tester"
    password: "psw"

backupcluster:
  name: "backup-cluster"
  address:
    ip: ""
    port:
      name: "backup-port"
      number: 3004
    dnsname: ""
  auth:
    username: "tester"
    password: "psw"

authenticator:
  enabled: true
  name: "authenticator"
  image:
    repository: "aerospike/aerospike-pitr-authenticator"
    tag: ""
    pullPolicy: ""
  port:
    name: "web"
    number: 8080
  serviceMonitor:
    enabled: false
    port:
      name: "metrics"
      number: 8080
  resources:
    requests:
      cpu: 0
    #      memory: ""
    limits:
      cpu: 0
  #      memory: ""
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  labels: { }
  annotations: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  config:
    auth:
      enabled: false
      username: "pitr"
      password: "pitrpwd"

compactor:
  enabled: true
  name: "compactor"
  image:
    repository: "aerospike/aerospike-pitr-compactor"
    tag: ""
    pullPolicy: ""
  port:
    name: "web"
    number: 8080
  serviceMonitor:
    enabled: false
    port:
      name: "metrics"
      number: 8088
  resources:
    requests:
      cpu: 0
    #      memory: ""
    limits:
      cpu: 0
  #      memory: ""
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  labels: { }
  annotations: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  config:
    host: "0.0.0.0"
    auth:
      enabled: false
      tokenRefreshSeconds: 82800
      username: "pitr-compactor"
      password: "pitr-compactor-pwd"
    backendTimeoutMs: 1000
    retryIntervalMs: 1000
    compactIntervalSeconds: 86400
    smdCompactIntervalSeconds: 82800
    deleteOldRecordsIntervalSeconds: 90000
    meterRegistryStepSeconds: 10
    circuitBreakerConfiguration:
      slidingWindowSize: 20
      minimumNumberOfCalls: 8
      slowCallDurationThreshold: 10
      permittedNumberOfCallsInHalfOpenState: 4
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5

queuehandler:
  enabled: true
  name: "queue-handler"
  image:
    repository: "aerospike/aerospike-pitr-queue-handler"
    tag: ""
    pullPolicy: ""
  port:
    name: "web"
    number: 8080
  serviceMonitor:
    enabled: false
    port:
      name: "metrics"
      number: 8088
  resources:
    requests:
      cpu: 0
    #      memory: ""
    limits:
      cpu: 0
  #      memory: ""
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  labels: { }
  annotations: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  config:
    host: "0.0.0.0"
    auth:
      enabled: false
      tokenRefreshSeconds: 82800
      username: "pitr-queue-handler"
      password: "pitr-queue-handler-pwd"
    backendTimeoutMs: 2000
    backendQueueProcessingTimeoutMs: 5000
    queueBatchSize: 100
    queueBatchDurationLimitMs: 2000
    queuePullingIntervalMs: 1000
    zombieRecoverIntervalMs: 60000
    recordRecoverThresholdMs: 600000
    retryIntervalMs: 1000
    meterRegistryStepSeconds: 10
    refreshQueueDetailsCacheSeconds: 5
    processingExecutorSize: 32
    circuitBreakerConfiguration:
      slidingWindowSize: 20
      minimumNumberOfCalls: 8
      slowCallDurationThreshold: 10
      permittedNumberOfCallsInHalfOpenState: 4
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5

smdhandler:
  enabled: true
  name: "smd-handler"
  image:
    repository: "aerospike/aerospike-pitr-smd-handler"
    tag: ""
    pullPolicy: ""
  port:
    name: "web"
    number: 8080
  serviceMonitor:
    enabled: false
    port:
      name: "metrics"
      number: 8088
  resources:
    requests:
      cpu: 0
    #      memory: ""
    limits:
      cpu: 0
  #      memory: ""
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  labels: { }
  annotations: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  config:
    host: "0.0.0.0"
    auth:
      enabled: false
      tokenRefreshSeconds: 82800
      username: "pitr-smd-handler"
      password: "pitr-smd-handler-pwd"
    backendTimeoutMs: 1000
    backupIntervalSeconds: 900
    retryIntervalMs: 1000
    meterRegistryStepSeconds: 10
    circuitBreakerConfiguration:
      slidingWindowSize: 20
      minimumNumberOfCalls: 8
      slowCallDurationThreshold: 10
      permittedNumberOfCallsInHalfOpenState: 4
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5

xdrscheduler:
  enabled: true
  name: "xdr-scheduler"
  image:
    repository: "aerospike/aerospike-pitr-xdr-scheduler"
    tag: ""
    pullPolicy: ""
  port:
    name: "web"
    number: 8080
  serviceMonitor:
    enabled: false
    port:
      name: "metrics"
      number: 8088
  resources:
    requests:
      cpu: 0
    #      memory: ""
    limits:
      cpu: 0
  #      memory: ""
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  labels: { }
  annotations: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  config:
    host: "0.0.0.0"
    auth:
      enabled: false
      tokenRefreshSeconds: 82800
      username: "pitr-xdr-scheduler"
      password: "pitr-xdr-scheduler-pwd"
    backendTimeoutMs: 2000
    xdrSchedulerIntervalMs: 10000
    xdrSchedulerCheckLagIntervalMs: 5000
    retryIntervalMs: 1000
    meterRegistryStepSeconds: 10
    circuitBreakerConfiguration:
      slidingWindowSize: 20
      minimumNumberOfCalls: 8
      slowCallDurationThreshold: 10
      permittedNumberOfCallsInHalfOpenState: 4
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5

restbackend:
  enabled: true
  name: "rest-backend"
  image:
    repository: "aerospike/aerospike-pitr-rest-backend"
    tag: ""
    pullPolicy: ""
  port:
    name: "web"
    number: 8080
  serviceMonitor:
    enabled: false
    port:
      name: "metrics"
      number: 8080
  resources:
    requests:
      cpu: 0
    #      memory: ""
    limits:
      cpu: 0
  #      memory: ""
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  labels: { }
  annotations: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  config:
    auth:
      enabled: false
      username: "pitr"
      password: "pitrpwd"
    backupMaxCommandsInProcess: 32
    backupMaxCommandsInQueue: 10000
    restBackendClientPolicyMaxConnsPerNode: 500
    backupCatalogNamespace: "catalog"
    meterRegistryStepSeconds: 10
    backgroundJobBatchSize: 100
    backgroundJobParallelism: 4

storageprovider:
  enabled: true
  name: "storage-provider"
  image:
    repository: "aerospike/aerospike-pitr-storage-provider"
    tag: ""
    pullPolicy: ""
  port:
    name: "web"
    number: 8081
  serviceMonitor:
    enabled: false
    port:
      name: "metrics"
      number: 8081
  resources:
    requests:
      cpu: 0
    #      memory: ""
    limits:
      cpu: 0
  #      memory: ""
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  labels: { }
  annotations: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  config:
    auth:
      enabled: false
    accessKey: "minioadmin"
    secretKey: "minioadmin"
    bucketname: "as-backup-bucket"

xdrtransformer:
  enabled: true
  name: "xdr-transformer"
  image:
    repository: "aerospike/aerospike-pitr-xdr-transformer"
    tag: ""
    pullPolicy: ""
  resources:
    requests:
      cpu: 0
    #      memory: ""
    limits:
      cpu: 0
  #      memory: ""
  replicas: 1
  serviceMonitor:
    enabled: false
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  labels: { }
  annotations: { }
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  config:
    service:
      name: "xdr-service"
      port: 8082
      address: 0.0.0.0
      ioThreads: 4
      workerThreads: 4
      maxConcurrentRecords: 32768
      clusterName: pitr
      manage:
        name: "xdr-manage"
        address: 0.0.0.0
        port: 8902
    logging:
      enableConsoleLogging: true
      file: /var/log/aerospike-xdr-proxy/aerospike-xdr-proxy.log
      tickerInterval: 1

minio:
  enabled: true
  name: "minio"
  address:
    name: "minio-port"
    ip: ""
    port: 9000

ingress:
  enable: true
  ingressClassName: "nginx"

prometheus:
  enable: false
  interval: 10s

