apiVersion: v2
name: aerospike-jms-outbound
description: A Helm chart for Aerospike Connect for JMS - Outbound
type: application
icon: https://avatars0.githubusercontent.com/u/2214313?s=200&v=4
keywords:
  - Aerospike
  - Connector
  - JMS
  - Outbound
  - Source
maintainers:
  - name: Aerospike
    email: developers@aerospike.com

# The helm chart version
version: "4.2.16"

# The default version of Aerospike JMS Outbound Connector
appVersion: "4.2.16"
