{{- if .Values.authenticator.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.authenticator.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.authenticator) .) | nindent 4 }}
data:
  AEROSPIKE_AUTH_ENABLEAUTH: {{ .Values.authenticator.config.auth.enabled | quote }}
  AEROSPIKE_AUTH_RESTBACKENDURI: http://{{ .Values.restbackend.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.restbackend.port.number }}
{{- end }}

{{- if .Values.compactor.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.compactor.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.compactor) .) | nindent 4 }}
data:
  config.yml: {{ tpl (.Files.Get "config/compactor-config.yml") . | toYaml | indent 2 }}
{{- end }}

{{- if .Values.queuehandler.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.queuehandler.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.queuehandler) .) | nindent 4 }}
data:
  config.yml: {{ tpl (.Files.Get "config/queue-handler-config.yml") . | toYaml | indent 2 }}
{{- end }}

{{- if .Values.smdhandler.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.smdhandler.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.smdhandler) .) | nindent 4 }}
data:
  config.yml: {{ tpl (.Files.Get "config/smd-handler-config.yml") . | toYaml | indent 2 }}
{{- end }}

{{- if .Values.xdrscheduler.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.xdrscheduler.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.xdrscheduler) .) | nindent 4 }}
data:
  config.yml: {{ tpl (.Files.Get "config/xdr-scheduler-config.yml") . | toYaml | indent 2 }}
{{- end }}

{{- if .Values.restbackend.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.restbackend.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.restbackend) .) | nindent 4 }}
data:
  AEROSPIKE_REST_BACKEND_ENABLEAUTH: {{ .Values.restbackend.config.auth.enabled | quote }}
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: {{ .Values.prometheus.enable | quote }}
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: {{ .Values.prometheus.enable | quote }}
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_STEP: {{ .Values.prometheus.interval | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,env"
  PITR_SERVICE_NAME: {{ .Values.restbackend.name }}
  AEROSPIKE_BACKUP_HOST: {{ .Values.backupcluster.name }}.{{ $.Release.Namespace }}.svc.cluster.local
  AEROSPIKE_BACKUP_PORT: {{ .Values.backupcluster.address.port.number | quote }}
  AEROSPIKE_BACKUP_CATALOGNAMESPACE: {{ .Values.restbackend.config.backupCatalogNamespace }}
  AEROSPIKE_XDR_PROXY_PORT: {{ .Values.xdrtransformer.config.service.port | quote }}
  AEROSPIKE_REST_BACKEND_STORAGEPROVIDERURI: http://{{.Values.storageprovider.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .Values.storageprovider.port.number }}
  AEROSPIKE_BACKUP_MAXCOMMANDSINPROCESS: {{ .Values.restbackend.config.backupMaxCommandsInProcess | quote }}
  AEROSPIKE_BACKUP_MAXCOMMANDSINQUEUE: {{ .Values.restbackend.config.backupMaxCommandsInQueue | quote }}
  AEROSPIKE_REST_BACKEND_CLIENTPOLICY_MAXCONNSPERNODE: {{ .Values.restbackend.config.restBackendClientPolicyMaxConnsPerNode | quote }}
  AEROSPIKE_REST_BACKEND_BACKGROUNDJOBPOLICY_RECORDSBATCHSIZE: {{ .Values.restbackend.config.backgroundJobBatchSize | quote }}
  AEROSPIKE_REST_BACKEND_BACKGROUNDJOBPOLICY_PARALLELISM: {{ .Values.restbackend.config.backgroundJobParallelism | quote }}
{{- end }}

{{- if and .Values.storageprovider.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.storageprovider.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.storageprovider) .) | nindent 4 }}
data:
  AEROSPIKE_STORAGE_PROVIDER_ENABLEAUTH: {{ .Values.storageprovider.config.auth.enabled | quote }}
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: {{ .Values.prometheus.enable | quote }}
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: {{ .Values.prometheus.enable | quote }}
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_STEP: {{ .Values.prometheus.interval | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,env"
  SERVER_PORT: {{ .Values.storageprovider.port.number | quote }}
  AEROSPIKE_STORAGE_PROVIDER_CONTAINERNAME: {{ .Values.storageprovider.config.bucketname | quote }}
  PITR_SERVICE_NAME: {{ .Values.storageprovider.name }}
  AEROSPIKE_STORAGE_PROVIDER_PROVIDERNAME: "AWS_S3"
  {{- if .Values.minio.enabled }}
  AMAZON_S3_SERVICEENDPOINT: http://{{ .Values.minio.name }}.{{ $.Release.Namespace  }}.svc.cluster.local:{{ .Values.minio.address.port }}
  {{- else }}
  AMAZON_S3_SERVICEENDPOINT: ""
  {{- end }}
{{- end }}

{{- if .Values.xdrtransformer.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.xdrtransformer.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.xdrtransformer) .) | nindent 4 }}
data:
  aerospike-xdr-proxy.yml:
{{ include "aerospike-xdr-proxy.config" . | toYaml | nindent 4 }}
{{- end }}

{{- if .Values.aws.ecrtokenissuer.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.aws.ecrtokenissuer.issuer.name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/part-of: {{ $.Chart.Name | trunc 63 | trimSuffix "-" | quote }}
  annotations:
    "helm.sh/hook": pre-install, post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  AWS_REGION: {{ .Values.aws.ecrtokenissuer.credentials.awsRegion | quote }}
  DOCKER_SECRET_NAME: {{ .Values.aws.ecrtokenissuer.secretname | quote }}
{{- end }}
