{{- if and (default .Values.autoscaling.enabled .Values.authenticator.autoscaling.enabled) .Values.authenticator.enabled}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.authenticator.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.authenticator) .) | nindent 4 }}
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ default .Values.autoscaling.targetCPUUtilizationPercentage .Values.authenticator.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.authenticator.autoscaling.minReplicas }}
  maxReplicas: {{ default .Values.autoscaling.maxReplicas .Values.authenticator.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.authenticator.name }}
{{- end }}


{{- if and (default .Values.autoscaling.enabled .Values.compactor.autoscaling.enabled) .Values.compactor.enabled}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.compactor.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.compactor) .) | nindent 4 }}
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ default .Values.autoscaling.targetCPUUtilizationPercentage .Values.compactor.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.compactor.autoscaling.minReplicas }}
  maxReplicas: {{ default .Values.autoscaling.maxReplicas .Values.compactor.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.compactor.name }}
{{- end }}

{{- if and (default .Values.autoscaling.enabled .Values.queuehandler.autoscaling.enabled) .Values.queuehandler.enabled}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.queuehandler.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.queuehandler) .) | nindent 4 }}
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ default .Values.autoscaling.targetCPUUtilizationPercentage .Values.queuehandler.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.queuehandler.autoscaling.minReplicas }}
  maxReplicas: {{ default .Values.autoscaling.maxReplicas .Values.queuehandler.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.queuehandler.name }}
{{- end }}

{{- if and (default .Values.autoscaling.enabled .Values.smdhandler.autoscaling.enabled) .Values.smdhandler.enabled}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.smdhandler.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.smdhandler) .) | nindent 4 }}
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ default .Values.autoscaling.targetCPUUtilizationPercentage .Values.smdhandler.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.smdhandler.autoscaling.minReplicas }}
  maxReplicas: {{ default .Values.autoscaling.maxReplicas .Values.smdhandler.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.smdhandler.name }}
{{- end }}

{{- if and (default .Values.autoscaling.enabled .Values.xdrscheduler.autoscaling.enabled) .Values.xdrscheduler.enabled}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.xdrscheduler.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.xdrscheduler) .) | nindent 4 }}
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ default .Values.autoscaling.targetCPUUtilizationPercentage .Values.xdrscheduler.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.xdrscheduler.autoscaling.minReplicas }}
  maxReplicas: {{ default .Values.autoscaling.maxReplicas .Values.xdrscheduler.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.xdrscheduler.name }}
{{- end }}

{{- if and (default .Values.autoscaling.enabled .Values.restbackend.autoscaling.enabled) .Values.restbackend.enabled}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.restbackend.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.restbackend) .) | nindent 4 }}
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ default .Values.autoscaling.targetCPUUtilizationPercentage .Values.restbackend.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.restbackend.autoscaling.minReplicas }}
  maxReplicas: {{ default .Values.autoscaling.maxReplicas .Values.restbackend.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.restbackend.name }}
{{- end }}

{{- if and (default .Values.autoscaling.enabled .Values.storageprovider.autoscaling.enabled) .Values.storageprovider.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.storageprovider.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.storageprovider) .) | nindent 4 }}
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ default .Values.autoscaling.targetCPUUtilizationPercentage .Values.storageprovider.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.storageprovider.autoscaling.minReplicas }}
  maxReplicas: {{ default .Values.autoscaling.maxReplicas .Values.storageprovider.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.storageprovider.name }}
{{- end }}

{{- if and (default .Values.autoscaling.enabled .Values.xdrtransformer.autoscaling.enabled) .Values.xdrtransformer.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.xdrtransformer.name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.xdrtransformer) .) | nindent 4 }}
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: {{ default .Values.autoscaling.targetCPUUtilizationPercentage .Values.xdrtransformer.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
      type: Resource
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.xdrtransformer.autoscaling.minReplicas }}
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.xdrtransformer.name }}
{{- end }}