{{- if .Values.restbackend.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.restbackend.name }}-rolebinding
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.restbackend) .) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $.Release.Namespace }}
    name: {{ .Values.restbackend.name }}-serviceaccount
roleRef:
  kind: Role
  name: {{ .Values.restbackend.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.aws.ecrtokenissuer.enabled }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.aws.ecrtokenissuer.issuer.name }}-rolebinding
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/part-of: {{ $.Chart.Name | trunc 63 | trimSuffix "-" | quote }}
  annotations:
    "helm.sh/hook": pre-install, post-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ .Values.aws.ecrtokenissuer.issuer.name }}-serviceaccount
    namespace: {{ $.Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.aws.ecrtokenissuer.issuer.name }}-role
  apiGroup: ""
{{- end}}

