{{- if .Values.smdhandler.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.smdhandler.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.smdhandler) .) | nindent 4 }}
spec:
  replicas: {{ default .Values.replicas .Values.smdhandler.replicas }}
  selector:
    matchLabels:
     {{- include "aerospike-enterprise-backup.selectorLabels" (merge (dict "component" .Values.smdhandler) .) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml (merge $.Values.smdhandler.annotations .) | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aerospike-enterprise-backup.selectorLabels" (merge (dict "component" .Values.smdhandler) .) | nindent 8 }}
        {{- with .Values.smdhandler.labels }}
        {{- . | toYaml | nindent 8}}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent 6}}
      volumes:
        - name: "configmap-volume"
          configMap:
            name: {{ .Values.smdhandler.name }}-configmap
      initContainers:
        {{- include "initContainer.wait.rest-backend" . | nindent 10 }}
        {{- include "initContainer.wait.authenticator" . | nindent 10 }}
        {{- include "initContainer.wait.storage-provider" . | nindent 10 }}
      containers:
        - name: {{ .Values.smdhandler.name}}
          image: {{ include "get-image" (merge (dict "component" .Values.smdhandler) .) }}
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.smdhandler.image.pullPolicy }}
          resources:
            requests:
              {{- default .Values.resources .Values.smdhandler.resources | toYaml | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/config
              name: "configmap-volume"
          ports:
            - name: {{ .Values.smdhandler.port.name }}
              containerPort: {{ .Values.smdhandler.port.number }}
              protocol: TCP
            {{- if .Values.smdhandler.serviceMonitor.enabled}}
            - name: {{ .Values.smdhandler.serviceMonitor.port.name }}
              protocol: TCP
              containerPort: {{ .Values.smdhandler.serviceMonitor.port.number }}
           {{- end }}
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            httpGet:
              path: /health
              port: {{ .Values.smdhandler.port.number }}
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            httpGet:
              path: /health
              port: {{ .Values.smdhandler.port.number }}
    {{- with .Values.smdhandler.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .Values.smdhandler.nodeSelector }}
      nodeSelector:
       {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .Values.smdhandler.tolerations }}
      tolerations:
       {{- . | nindent 8 }}
    {{- end }}
{{- end }}