{{- if .Values.storageprovider.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.storageprovider.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.storageprovider) .) | nindent 4 }}
spec:
  replicas: {{ default .Values.replicas .Values.storageprovider.replicas }}
  selector:
    matchLabels:
      {{- include "aerospike-enterprise-backup.selectorLabels" (merge (dict "component" .Values.storageprovider) .) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml (merge $.Values.storageprovider.annotations .) | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aerospike-enterprise-backup.selectorLabels" (merge (dict "component" .Values.storageprovider) .) | nindent 8 }}
        {{- with .Values.storageprovider.labels }}
        {{- . | toYaml | nindent 8}}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent 6 }}
      {{- if (lookup "v1" "ServiceAccount" $.Release.Namespace .Values.storageprovider.name) }}
      serviceAccountName: {{ .Values.storageprovider.name }}
      {{- end }}
      initContainers:
        {{- include "initContainer.wait.authenticator" . | nindent 10 }}
      containers:
        - name: {{ .Values.storageprovider.name }}
          image: {{ include "get-image" (merge (dict "component" .Values.storageprovider) .) }}
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.storageprovider.image.pullPolicy }}
          resources:
            requests:
              {{- default .Values.resources .Values.storageprovider.resources | toYaml | nindent 12 }}
          ports:
            - name: {{ .Values.storageprovider.port.name }}
              containerPort: {{ .Values.storageprovider.port.number }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.storageprovider.name }}-configmap
            - secretRef:
                optional: true
                name: {{ .Values.storageprovider.name }}-secret
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /health
              port: {{ .Values.storageprovider.port.number }}
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /health
              port: {{ .Values.storageprovider.port.number }}
    {{- with .Values.storageprovider.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .Values.storageprovider.nodeSelector }}
      nodeSelector:
       {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .Values.storageprovider.tolerations }}
      tolerations:
       {{- . | nindent 8 }}
    {{- end }}
{{- end }}