{{- if .Values.xdrscheduler.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.xdrscheduler.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.xdrscheduler) .) | nindent 4 }}
spec:
  replicas: {{ default .Values.replicas .Values.xdrscheduler.replicas }}
  selector:
    matchLabels:
      {{- include "aerospike-enterprise-backup.selectorLabels" (merge (dict "component" .Values.xdrscheduler) .) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml (merge $.Values.xdrscheduler.annotations .) | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aerospike-enterprise-backup.selectorLabels" (merge (dict "component" .Values.xdrscheduler) .) | nindent 8 }}
        {{- with .Values.xdrscheduler.labels }}
        {{- . | toYaml | nindent 8}}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent 6}}
      volumes:
        - name: "configmap-volume"
          configMap:
            name: {{ .Values.xdrscheduler.name }}-configmap
      initContainers:
        {{- include "initContainer.wait.rest-backend" . | nindent 10 }}
        {{- include "initContainer.wait.authenticator" . | nindent 10 }}
        {{- include "initContainer.wait.storage-provider" . | nindent 10 }}
      containers:
        - name: {{ .Values.xdrscheduler.name}}
          image: {{ include "get-image" (merge (dict "component" .Values.xdrscheduler) .) }}
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.xdrscheduler.image.pullPolicy }}
          resources:
            {{- default .Values.resources .Values.xdrscheduler.resources | toYaml | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/config
              name: "configmap-volume"
          ports:
            - name: {{ .Values.xdrscheduler.port.name }}
              containerPort: {{ .Values.xdrscheduler.port.number }}
              protocol: TCP
            {{- if .Values.xdrscheduler.serviceMonitor.enabled }}
            - name: {{ .Values.xdrscheduler.serviceMonitor.port.name }}
              containerPort: {{ .Values.xdrscheduler.serviceMonitor.port.number }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            httpGet:
              path: /health
              port: {{ .Values.xdrscheduler.port.number }}
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            httpGet:
              path: /health
              port: {{ .Values.xdrscheduler.port.number }}
    {{- with .Values.xdrscheduler.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .Values.xdrscheduler.nodeSelector }}
      nodeSelector:
       {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .Values.xdrscheduler.tolerations }}
      tolerations:
       {{- . | nindent 8 }}
    {{- end }}
{{- end }}