apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike
spec:
  aerospikeConfig:
    namespaces:
      - name: test
        replication-factor: 2
        storage-engine:
          data-size: 1073741824
          type: memory
    network:
      fabric:
        port: 3001
      heartbeat:
        port: 3002
      service:
        port: 3000
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
  image: 'aerospike/aerospike-server-enterprise:7.1.0.0'
  podSpec:
    multiPodPerHost: true
  size: 1
  storage:
    volumes:
      - aerospike:
          path: /etc/aerospike/secret
        name: aerospike-config-secret
        source:
          secret:
            secretName: aerospike-secret
  validationPolicy:
    skipWorkDirValidate: true
    skipXdrDlogFileValidate: true