proxyConfig:
  service:
    ports:
      4000: { }
    manage:
      4040: { }
  aerospike:
    seeds:
      - aerocluster-0-0.aerospike.svc.cluster.local:
          port: 3000
imagePullSecrets:
  - name: regcred
