# Default values for aerospike-vector-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "aerospike/aerospike-proximus"
  pullPolicy: "IfNotPresent"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.4.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

aerospikeVectorSearchConfig: {}
#service: # Required
#  io-threads: <io-threads> # Optional default: retrieved from the system
#  worker-threads: <worker-threads> # Optional default: retrieved from the system
#  max-inbound-message-size: <max-inbound-message-size> # Optional default: 8388608 (8MiB)
#  max-concurrent-requests: <max-concurrent-requests> # Optional default: 32768
#  http2-max-concurrent-streams: <http2-max-concurrent-streams> # Optional default: 128
#  flow-control: # Optional
#    memory-high-water-mark-percentage: <memory-high-water-mark-percentage> # Optional default: 80
#    memory-low-water-mark-percentage: <memory-low-water-mark-percentage> # Optional default: 60
#    period: <period> # Optional default: 10
#    stream-ready-timeout: <stream-ready-timeout> # Optional default: 10,000 milliseconds
#    minimum-enable-time: <minimum-enable-time> # Optional default: 10,000 milliseconds
#  ports: # Required
#    5000:
#      addresses:
#        "0.0.0.0"
#  advertised-listeners: # Optional
#    default:
#      - address: 10.0.0.1
#        port: 5000
#  metadata-namespace: <metadata-namespace> # Optional default: proximus-meta
#  graceful-shutdown-timeout: <graceful-shutdown-timeout> # Optional default: 20,000 milliseconds
#
#manage: # Optional
#  ports:
#    5040: { }
#
#interconnect: # Required
#  ports:
#    5001:
#      addresses:
#        "0.0.0.0"
#  client-tls-id: <client-tls-id> # Optional
#  max-connections: <max-connections>  # Optional
#  max-total-connections: <max-total-connections> # Optional default: 32767
#  connect-timeout: <connect-timeout> # Optional default: 10000
#  io-threads: <io-threads> # Optional default: retrieved from the system
#  worker-threads: <worker-threads> # Optional default: retrieved from the system
#  max-inbound-message-size: <max-inbound-message-size> # Optional default: 8388608 (8MiB)
#  max-concurrent-requests: <max-concurrent-requests> # Optional default: 32768
#  http2-max-concurrent-streams": <http2-max-concurrent-streams> # Optional default: 128
#  flow-control: # Optional
#    memory-high-water-mark-percentage: <memory-high-water-mark-percentage> # Optional default: 80
#    memory-low-water-mark-percentage: <memory-low-water-mark-percentage> # Optional default: 60
#    period: <period> # Optional default: 10
#    stream-ready-timeout: <stream-ready-timeout> # Optional default: 10,000 milliseconds
#    minimum-enable-time: <minimum-enable-time> # Optional default: 10,000 milliseconds
#  rtt-max: <rtt-max> # Optional default: 5
#
#heartbeat: # Optional
#  interval: <interval> # Optional default: 500 milliseconds
#  timeout: <timeout> # Optional default: 5000 milliseconds
#  seeds: # Optional
#    - address: "10.0.0.1"
#      port: "5001"
#
#cluster: # Required
#  node-id: <id> # Optional
#  cluster-name: <cluster-name> # Required
#  min-cluster-size: <int> # Optional minimum allowed cluster size
#
#aerospike: # Required
#  seeds:  # Required
#    - "10.0.0.1"
#        port: 3000
#  client-policy: <client-policy>
#
#security:
#  auth-token: <auth-token> # Required
#  timeout: <timeout> # Optional default 2000 milliseconds
#  cache-expiry: <expiry>  # Optional default 10,000 milliseconds
#
#logging: # Optional
#  enable-console-logging: false
#  format: simple
#  max-history: 30
#  levels:
#    metrics-ticker: info
#    root: debug
#    ticker-interval: 10
#
#feature-key-file: "/etc/aerospike-proximus/features.conf" # Required
#
#indexing: # Optional
#  cache: # Optional
#    max-entries: <max-entries> # Optional default: 2,000,000
#    expiry-millis: <expiry-millis> # Optional default: 2^63-1
#  cleanup: # Optional
#    dropped-index-cleanup-scheduler-delay: <dropped-index-cleanup-scheduler-delay> # Optional default: 30 minutes
#    dropped-index-cleanup-scheduler-initial-delay: <dropped-index-cleanup-scheduler-initial-delay> # Optional default: 30 minutes
#    mark-dropped-index-clean-after: <mark-dropped-index-clean-after> # Optional default: 1 Hour
#    deleted-index-retention-time: <deleted-index-retention-time> # Optional default: 5 Days
#  batch-merge: # Optional
#    parallelism: <parallelism> # Optional default: retrieved from the system
#    executor-delay: <executor-delay> # Optional default: 1 Second
#    executor-initial-delay: <executor-initial-delay:> # Optional default: 0
#  enable-proxy-load-balancing: <enable-proxy-load-balancing> # Optional default: true
#
#tls: ""


initContainers: []

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  enabled: false
  annotations: {}
  labels: {}
  type: LoadBalancer
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  loadBalancerClass: ""
  externalTrafficPolicy: ""
  sessionAffinity: ""
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - name: "svc-port"
      port: 80
      targetPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


# Additional volumes on the output Deployment definition.
extraVolumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
extraVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
extraSecretVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true


nodeSelector: {}

tolerations: []

affinity: {}
