# Default values for aerospike-vector-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "aerospike/aerospike-proximus"
  pullPolicy: "IfNotPresent"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.4.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

aerospikeVectorSearchConfig:
  cluster:
    # TODO Figure out how to Add node-id field
    cluster-name: "avs-db-1"
  feature-key-file: "/etc/aerospike-proximus/features.conf"
  service:
    # Required when running behind NAT
    #    advertised-listeners:
    #     List of externally accessible addresses and ports for this AVS instance.
    #      default:
    #        - address: 10.0.0.1
    #          port: 5000
    ports:
      5000:
        addresses:
          "0.0.0.0"
#    cluster-name: "product-name"
    #max-inbound-message-size: 8388608
    #flow-control:
      # TODO Give reasonable example values for io-threads
      # io-threads: 4
      # TODO Give reasonable example values for worker-threads
      # worker-threads: 4
      #memory-high-water-mark-percentage: 80
      #memory-low-water-mark-percentage: 60
      #period: 10
      #stream-ready-timeout: 10000
      #minimum-enable-time: 10000
  manage:
    ports:
      5040: {}
  interconnect:
    ports:
      5001:
        addresses:
          "0.0.0.0"
  #heartbeat:
    # TODO Not clear how seeds should be look like
    # seeds:
    # - address: "127.0.0.1"
    #   port: 5001
    #interval: 500
    #timeout: 5000
  aerospike:
    metadata-namespace: "avs-meta"
    seeds:
      - 127.0.0.1:
          port: 3000
    #client-policy:
      # TODO Give reasonable name for cluster-name
      #cluster-name: "aerospike-cluster"
      # TODO Give reasonable value for unary-event-loops
      #            unary-event-loops: 4
      #batch-event-loops: 1
      #query-event-loops: 1
      #auth-mode: "INTERNAL"
      #timeout: 1000
      #login-timeout: 5000
      #close-timeout: 0
      #min-conns-per-node: 0
      #max-conns-per-node: 100
      #conn-pools-per-node: 1
      #max-socket-idle: 0
      #max-error-rate: 0
      #error-rate-window: 1
      #tend-interval: 1000
      #use-services-alternate: false
  #      keep-alive: ""
  #      ip-map: ""
  #      rack-aware: ""
  #      rack-id: ""
  #      rack-ids: ""
  #indexing:
    #cache:
      #max-entries: 5000000
  #     TODO Set some resonable value for expiry-millis field
  #      expiry-millis: 300000
  logging:
    #    file: /var/log/aerospike-proximus/aerospike-proximus.log
    enable-console-logging: false
    format: simple
    max-history: 30
    levels:
      metrics-ticker: info
      root: debug
    ticker-interval: 10


initContainers: []

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  enabled: false
  annotations: {}
  labels: {}
  type: LoadBalancer
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  loadBalancerClass: ""
  externalTrafficPolicy: ""
  sessionAffinity: ""
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - name: "svc-port"
      port: 80
      targetPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


# Additional volumes on the output Deployment definition.
extraVolumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
extraVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
extraSecretVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true


nodeSelector: {}

tolerations: []

affinity: {}
