proximusConfig:
  aerospike:
    metadata-namespace: "proximus-meta"
    seeds:
      - aerospike-cluster-0-0.aerospike-cluster.aerospike.svc.cluster.local:
          port: 3000
  logging:
    #    file: /var/log/aerospike-proximus/aerospike-proximus.log
    enable-console-logging: false
    format: simple
    max-history: 30
    levels:
      metrics-ticker: info
      root: info
    ticker-interval: 10

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 0

service:
  enabled: false
  type: ClusterIP
  ports:
    - name: "svc-port"
      port: 5000
      targetPort: 5000

ingress:
  enabled: false
  className: "nginx"
  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - paths:
        - path: /
          pathType: Prefix
          host: "as-quote-search-aerospike-proximus.aerospike.svc.cluster.local"