proximusConfig:
  aerospike:
    metadata-namespace: "proximus-meta"
    seeds:
      - aerospike-cluster-0-0.aerospike-cluster.aerospike.svc.cluster.local:
          port: 3000
  logging:
    #    file: /var/log/aerospike-proximus/aerospike-proximus.log
    enable-console-logging: false
    format: simple
    max-history: 30
    levels:
      metrics-ticker: info
      root: info
    ticker-interval: 10

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 0

service:
  enabled: true