backendUri: http://{{ $.Values.restbackend.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.restbackend.port.number }}
backendTimeoutMs: {{ $.Values.compactor.config.backendTimeoutMs }}
httpHost: {{ $.Values.compactor.config.host }}
httpPort: {{ $.Values.compactor.port.number }}
authenticatorUri: http://{{ $.Values.authenticator.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.authenticator.port.number }}
auth:
  enabled: {{ $.Values.compactor.config.auth.enabled }}
  tokenRefreshSeconds: {{ $.Values.compactor.config.auth.tokenRefreshSeconds }}
  username: {{ $.Values.compactor.config.auth.username }}
  password: {{ $.Values.compactor.config.auth.password }}
retryIntervalMs: {{ $.Values.compactor.config.retryIntervalMs }}
compactIntervalSeconds: {{ $.Values.compactor.config.compactIntervalSeconds }}
smdCompactIntervalSeconds: {{ $.Values.compactor.config.smdCompactIntervalSeconds }}
deleteOldRecordsIntervalSeconds: {{ $.Values.compactor.config.deleteOldRecordsIntervalSeconds }}
meterRegistryStepSeconds: {{ $.Values.compactor.config.meterRegistryStepSeconds }}
circuitBreakerConfiguration:
  slidingWindowSize: {{ $.Values.compactor.config.circuitBreakerConfiguration.slidingWindowSize }}
  minimumNumberOfCalls: {{ $.Values.compactor.config.circuitBreakerConfiguration.minimumNumberOfCalls }}
  slowCallDurationThreshold: {{ $.Values.compactor.config.circuitBreakerConfiguration.slowCallDurationThreshold }}
  permittedNumberOfCallsInHalfOpenState: {{ $.Values.compactor.config.circuitBreakerConfiguration.permittedNumberOfCallsInHalfOpenState }}
  automaticTransitionFromOpenToHalfOpenEnabled: {{ $.Values.compactor.config.circuitBreakerConfiguration.automaticTransitionFromOpenToHalfOpenEnabled | quote }}
  waitDurationInOpenState: {{ $.Values.compactor.config.circuitBreakerConfiguration.waitDurationInOpenState }}