---
global:
  scrape_interval: 10s
  scrape_timeout: 7s

scrape_configs:
  - job_name: rest-backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - rest-backend:8080

  - job_name: storage-provider
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - storage-provider:8081

  - job_name: compactor-system
    metrics_path: /metrics
    static_configs:
      - targets:
          - compactor:8088

  - job_name: queue-handler-system
    metrics_path: /metrics
    static_configs:
      - targets:
          - queue-handler:8088

  - job_name: smd-handler-system
    metrics_path: /metrics
    static_configs:
      - targets:
          - smd-handler:8088

  - job_name: xdr-scheduler-system
    metrics_path: /metrics
    static_configs:
      - targets:
          - xdr-scheduler:8088

  - job_name: compactor
    metrics_path: /prometheus
    static_configs:
      - targets:
          - compactor:8080

  - job_name: queue-handler
    metrics_path: /prometheus
    static_configs:
      - targets:
          - queue-handler:8080

  - job_name: smd-handler
    metrics_path: /prometheus
    static_configs:
      - targets:
          - smd-handler:8080

  - job_name: xdr-scheduler
    metrics_path: /prometheus
    static_configs:
      - targets:
          - xdr-scheduler:8080

  - job_name: xdr-transformer
    metrics_path: /manage/rest/v1/prometheus
    static_configs:
      - targets:
          - xdr-transformer:8902