{{- if .Values.minio.enabled }}
---
kind: Endpoints
apiVersion: "v1"
metadata:
  name: {{ .Values.minio.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.selectorLabels" (merge (dict "component" .Values.minio) .) | nindent 6 }}
subsets:
  - addresses:
      - ip: {{ .Values.minio.address.ip }}
    ports:
      - name: {{ .Values.minio.address.name | quote }}
        port: {{ .Values.minio.address.port }}
{{- end }}

{{- if .Values.backupcluster.address.ip }}
---
kind: Endpoints
apiVersion: "v1"
metadata:
  name: {{ .Values.backupcluster.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aerospike-enterprise-backup.labels" (merge (dict "component" .Values.backupcluster) .) | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .Values.backupcluster.address.ip | quote }}
    ports:
      - name: {{ .Values.backupcluster.address.port.name | quote }}
        port: {{ .Values.backupcluster.address.port.number }}
{{- end }}

{{- range $index, $ip := .Values.sourceclusters.addresses.ips -}}
{{ $name :=(printf "%s-%d" $.Values.sourceclusters.nameprefix $index) }}
---
kind: Endpoints
apiVersion: "v1"
metadata:
  name: {{ $name | quote }}
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/name: {{ $name | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/version: {{ default $.Chart.AppVersion $.Values.image.tag | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/part-of: {{ $.Chart.Name | trunc 63 | trimSuffix "-" | quote }}
subsets:
  - addresses:
      - ip: {{ $ip | quote }}
    ports:
      - name: {{ $.Values.sourceclusters.port.name | quote }}
        port: {{ $.Values.sourceclusters.port.number }}
{{- end }}
