apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aerospike-proxy.fullname" . }}-cm
  labels:
    {{- include "aerospike-proxy.labels" . | nindent 4 }}
data:
  aerospike-proxy.yml: |-
    {{- .Values.proxyConfig | toYaml | nindent 4 }}