configmap:
  create: true
namespace: "aerospike"
image:
  repository: aerospike.jfrog.io/ecosystem-container-dev-local/aerospike-backup-service
  tag: tests
imagePullSecrets:
  - name: regcred
backupServiceConfig:
  aerospike-clusters:
    absCluster1:
      seed-nodes:
        - host-name: "aerospike-cluster"
          port: 3000
      credentials:
        user: tester
        password: psw
  storage:
    minioStorage:
      s3-storage:
        path: minioStorage
        # as-backup-bucket is expected to exist in MinIO.
        bucket: as-backup-bucket
        s3-region: eu-central-1
        s3-profile: minio
        s3-endpoint-override: http://minio:9000
  backup-policies:
    keepFilesPolicy:
      # Run backup operations in a single thread.
      parallel: 1
      # Previous full backups are not deleted when a new one is created.
      remove-files: KeepAll
  backup-routines:
    minioKeepFilesRoutine:
      # 24 hours interval for full backups.
      interval-cron: "@daily"
      # 1 hour interval for incremental backups.
      incr-interval-cron: "@hourly"
      source-cluster: absCluster1
      storage: minioStorage
      namespaces: [ "test" ]
      backup-policy: keepFilesPolicy
volumes:
  - name: psw
    secret:
      secretName: psw-cm
      optional: false
  - name: credentials
    secret:
      secretName: credentials
      optional: false
extraSecretVolumeMounts:
  - name: psw
    mountPath: /config/psw.txt
    subPath: psw.txt
    readOnly: true
  - name: credentials
    mountPath: /root/.aws/credentials
    subPath: credentials
    readOnly: true