apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aerospike-backup-service.fullname" . }}-cm
  labels:
    {{- include "aerospike-backup-service.labels" . | nindent 4 }}
data:
  aerospike-backup-service.yml: |-
    {{- .Values.backupServiceConfig | toYaml | nindent 4 }}
