apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: avs-gw
  namespace: aerospike
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 5433
        name: grpc-svc
        protocol: tls
      hosts:
        - "*"
      tls:
        mode: PASSTHROUGH
