apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aerospike-vector-search.fullname" . }}
  labels:
    {{- include "aerospike-vector-search.labels" . | nindent 4 }}
data:
  aerospike-proximus.yml: |-
    {{- .Values.aerospikeVectorSearchConfig | toYaml | nindent 4 }}
