---
apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerospike-cluster
  namespace: aerospike
spec:
  size: 3
  image: aerospike/aerospike-server-enterprise:7.0.0.5

  podSpec:
    multiPodPerHost: false

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    volumes:
      - name: workdir
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Filesystem
            size: 3Gi
        aerospike:
          path: /opt/aerospike
      - name: nsvol1
        aerospike:
          path: /mnt/disks/test
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Filesystem
            size: 5Gi
      - name: nsvol2
        aerospike:
          path: /mnt/disks/proximus
        source:
          persistentVolume:
            storageClass: ssd
            volumeMode: Filesystem
            size: 5Gi
      - name: aerospike-config-secret
        source:
          secret:
            secretName: aerospike-secret
        aerospike:
          path: /etc/aerospike/secret

  #  aerospikeAccessControl:
  #    users:
  #      - name: admin
  #        secretName: auth-secret
  #        roles:
  #          - sys-admin
  #          - user-admin

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    #    security: {}
    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002
    namespaces:
      - name: test
        replication-factor: 2
        storage-engine:
          type: device
          filesize: 5368709120
          files:
            - /mnt/disks/test/test.dat
      - name: proximus-meta
        nsup-period: 600
        nsup-threads: 2
        evict-tenths-pct: 5
        replication-factor: 2
        storage-engine:
          type: device
          filesize: 5368709120
          files:
            - /mnt/disks/proximus/proximus.dat
