replicaCount: 3
aerospikeVectorSearchConfig:
  cluster:
    cluster-name: "avs-db-1"
  feature-key-file: "/etc/aerospike-vector-search/features.conf"
  service:
    ports:
      5000:
        addresses:
          "0.0.0.0"
  manage:
    ports:
      5040: { }

  heartbeat:
    seeds:
      - address: avs-gke-aerospike-vector-search-0.avs-gke-aerospike-vector-search.aerospike.svc.cluster.local
        port: 5001
  interconnect:
    ports:
      5001:
        addresses:
          0.0.0.0
  aerospike:
    seeds:
      - aerospike-cluster-0-0.aerospike-cluster.aerospike.svc.cluster.local:
          port: 3000
  logging:
    #    file: /var/log/aerospike-vector-search/aerospike-vector-search.log
    enable-console-logging: false
    format: simple
    max-history: 30
    levels:
      metrics-ticker: info
      root: info
    ticker-interval: 10

service:
  enabled: false
  type: LoadBalancer
  annotations:
    cloud.google.com/l4-rbs: "enabled"
#    networking.gke.io/load-balancer-type: "Internal"
  ports:
    - name: "svc-port"
      port: 5000
      targetPort: 5000

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
                - "aerospike-vector-search"
