apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphservice.fullname" . }}
  namespace: {{ include "aerospike-graph.namespace" . }}
  labels:
    {{- include "graphservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: service
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      appProtocol: http
    - name: healthcheck
      port: {{ .Values.service.livenessProbePort }}
      targetPort: {{ .Values.livenessProbe.port }}
      appProtocol: http
  selector:
    {{- include "graphservice.selectorLabels" . | nindent 4 }}
