# Headless service for stable DNS entries for the pods.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aerospike-kafka-outbound.fullname" . }}
  labels:
    app: {{ include "aerospike-kafka-outbound.fullname" . }}
    {{- include "aerospike-kafka-outbound.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ include "aerospike-kafka-outbound.fullname" . }}
    port: {{ include "aerospike-kafka-outbound.servicePort" . }}
  clusterIP: None
  selector:
    app: {{ include "aerospike-kafka-outbound.fullname" . }}
