ingress:
  enabled: true
  className: "nginx"
  hosts:
    - paths:
        - path: /
          pathType: Prefix
          
quoteSearchConfig:
  proximusHost: "as-quote-search-aerospike-proximus.aerospike.svc.cluster.local"
